<a target="_blank" rel="noopener noreferrer" href="https://colab.research.google.com/github/stanbaek/ece487/blob/main/docs/Labs/PythonContainers.ipynb">![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)</a>

# Python Containers & Numpy

## Purpose
This in-class exercise (ICE) will introduce Python data containers, such as lists, tuples, and strings.  It will also introduce NumPy, a fundametal package for scientific computing in Python.

<hr>

## Strings, Lists, Tuples, and Dictionaries

Reference: D. Beazley, Python Essential Reference, 4th ed, Addison Wesley, 2009

### Strings

To create string literals, enclose them in single, double, or triple quotes as follows

In [1]:
a = "Hellow World"
b = 'Python is groovy'
c = """Computer says 'No'"""
print(a)
print(b)
print(c)

Hellow World
Python is groovy
Computer says 'No'


The same type of quote used to start a string must be used to terminate it.  Triple-quoted strings capture all the text that appears prior to the terminating triple quote, as opposed to single- and double-quoted strings, which must be  specified on one logical line.  Triple-quoted strings are useful when the contents of a string literal span multiple lines of text such as the following:

In [ ]:
print('''Content-type: text/html

<h1> Hello World </h1>
Click <a href="http://www.python.org">here</a>.
''')

Strings are stored as sequences of characters indexed by integers starting at zero

In [1]:
a = "Hello World"
print(a[4])
print(a[:5])
print(a[6:])
print(a[3:8])

o
Hello
World
lo Wo


In [8]:
x = "37"
y = "42"
z = x+y
print(z) # what does this print?  why?
z = int(x)+int(y)
print(z)  # what does this print?

3742
79


### Lists
Lists are sequences of arbitrary objects. You create a list by enclosing values in square brackets, as follows:

In [8]:
names = ["Dave", "Mark", "Ann", "Phil"]
print(names)

['Dave', 'Mark', 'Ann', 'Phil']


Lists are indexed by integers, starting with zero. Use the indexing operator to access and modify individual items of the list:

In [9]:
a = names[2]
print(a)
names[0] = "Jeff"
names.append("Paula")
names.insert(2, "Thomas")
print(names)

Ann
['Jeff', 'Mark', 'Thomas', 'Ann', 'Phil', 'Paula']


Lists can be sliced:
```Python
x[start:stop:stride]
```

In [10]:
b = names[0:2]
print(b)
c = names[2:]
print(c)
names[1] = 'Jeff'
print(names)
names[0:2] = ['Dave', 'Mark', 'Jeff']
print(names)

['Jeff', 'Mark']
['Thomas', 'Ann', 'Phil', 'Paula']
['Jeff', 'Jeff', 'Thomas', 'Ann', 'Phil', 'Paula']
['Dave', 'Mark', 'Jeff', 'Thomas', 'Ann', 'Phil', 'Paula']


Use the plus `+` operator to concatenate lists: 

In [11]:
a = [1,2,3]+[4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


An empty list can be created bin one of two ways

In [5]:
names = []
print(names)
names = list()
print(names)

[]
[]


Lists can contain any kind of Python object, including other lists, as in the following example:

In [6]:
a = [1, "Dave", 3.14, ["Mark", 7, 9, [0, 101]], 10]

Items contained in nested lists are accessed by applying more than one indexing operation, as follows:

In [ ]:
print(a[1])
print(a[3])
print(a[3][1])
print(a[3][3][1])

Objects can be inserted and appended to a list.

In [ ]:
# List methods (insert)
list_b.insert(2,'python')
print(list_b)

In [ ]:
# List methods (append)
list_b.append('.')
print(list_b)

### Tuples
To create sinple data structures, you can pack a collection of values together into a single object using a *tuple*. You can create a tuple by enclosing group of values in parentheses like this: 

In [12]:
stock = ("GOOG", 100, 490.10)
address = ('www.python.org', 80)
person = ("Stan", "Baek", "stanley.baek@afacademy")

Python often recognizes that a tuple is intended enve if the parentheses are missing

In [13]:
stock = "GOOG", 100, 490.10
address = 'www.python.org', 80
person = "Stan", "Baek", "stanley.baek@afacademy"

For completeness, 0- and 1-element tuples can be defined, but have special syntax:

In [14]:
a = ()    # 0-tuple, empty tuple
b = (1,)  # 1-tuple  
c = 1,    # 1-tuple
print(type(a))
print(type(b))
print(type(c))
b = (1)
c = 1
print(type(b))
print(type(c))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'int'>
<class 'int'>


The values in a tuple can be extracted by numerical index just like a list. However, it is more common to unpack tuples into a set of variables like this

In [15]:
name, shares, price = stock
host, port = address
first_name, last_name, phone = person

Although tuples support most of the same operations as lists, such as indexing, slicing, and concatenation, the contents of a utple cannot be modified after creation.  That is, you cannot replace, delete, or append new elements to an exisiting tuple. 

In [16]:
print(stock[1]) 
stock[1] = 200  # error

100


TypeError: 'tuple' object does not support item assignment

### Dictionaries
- In Python, a dictionary (or dict) is mapping between a set of indices (keys) and a set of values
- The items in a dictionary are key-value pairs
- Keys can be any Python data type
- Dictionaries are unordered

In [1]:
# Dictionaries
eng2sp = {}
eng2sp['one'] = 'uno'
print(eng2sp)

{'one': 'uno'}


In [18]:
eng2sp = {'one': 'uno', 'two': 'dos', 'three': 'tres'}
print(eng2sp)

{'one': 'uno', 'two': 'dos', 'three': 'tres'}


In [19]:
# keys vs values
print(eng2sp.keys())
print(eng2sp.values())

dict_keys(['one', 'two', 'three'])
dict_values(['uno', 'dos', 'tres'])


<hr>

## NumPy

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type. In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in 3D space, ```[1, 2, 1]```, has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.
```
[[1., 0., 0.],
 [0., 1., 2.]]
 ```
 
Reference: ```https://numpy.org/doc/stable/user/quickstart.html```

### Installing NumPy System-wide
Open Windows Terminal and run
```
pip install numpy
```
If it returns an error message similar to
```
WARNING: You are using pip version 21.3.1; however, version 22.0 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
```
run
```
python.exe -m pip install --upgrade pip

```

### Installing NumPy for PyCharm Projects 
Open Your PyCharm project. Then, go to File > Settings > Project > Python Interpreter. Click `+` as shown below 



![SQRT](../images/PythonInterpreter.png)


Search for `numpy` and choose the `numpy` package. Click `Install Package` at the bottom.  Once the installation is complete, it will display `Package 'numpy' installed successfully`.  Close the window. `numpy` should be on the intalled packages list. 

In the future, you need to run the same procedure to install packages in PyCharm.  The packages we need include spatialmath-python, matplotlib, roboticstoolbox-python, and opencv-python.

### Creating Array
You can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [ ]:
import numpy as np
a = np.array([2, 3, 4])
print(type(a))
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(type(b))
print(b.dtype)

A frequent error consists in calling array with multiple arguments, rather than providing a single sequence as an argument
```Python
a = np.array(1, 2, 3, 4)    # WRONG
Traceback (most recent call last):
  ...
TypeError: array() takes from 1 to 2 positional arguments but 4 were given
a = np.array([1, 2, 3, 4])  # RIGHT
```

`np.array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print(b[0])
print(b[0][0]) 
print(b[0,0])

The function `np.zeros` creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [ ]:
a = np.zeros((2, 6))
print(a)
b = np.ones((2, 3, 4), dtype=np.int16)
print(b)
c = np.empty((4, 5))
print(c)

To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in range, but returns an array.

In [ ]:
a = np.arange(10, 30, 5)  
print(a)
b = np.arange(0, 2, 0.3)  
print(b)

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:

In [ ]:
a = np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
print(a)
b = np.linspace(0, 2 * np.pi, 100)        # useful to evaluate function at lots of points
print(b)

### Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array([20, 30, 40, 50])
print(a)
b = np.arange(4)
print(b)
c = a - b
print(c)
d = b**2
print(d)
e = 10 * np.sin(a)
print(e)
print(a < 35)

<span style="color:red">**IMPORTANT**</span>
Unlike in many matrix languages, the product operator `*` operates **elementwise** in NumPy arrays. The matrix product can be performed using the `@` operator (in python >=3.5) or the dot function or method:

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A*B)   # elementwise product
print(A@B)   # matrix product
print(np.matmul(A,B)) # matrix product
print(A.dot(B))  # matrix product

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [ ]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
print(a)
b = rg.random((2, 3))
print(b)
a *= 3
print(a)
b += a
print(b)
a += b  # b is not automatically converted to integer type

<span style="color:red">**IMPORTANT**</span>
A Python `list` cannot directly handle a mathematical operations, while numpy `array` can.  This is one of the main differences between a `list` and `array`. While you can store an integer or float in a list, you can’t really do mathematical operations in it.

In [2]:
import numpy as np
a = np.array([1,2,3])  # np array
print(a+a)
print(a*3)
print(a**2)

b = [1,2,3] # python list
print(b+b)
print(b*3)
print(b**2) # Error

[2 4 6]
[3 6 9]
[1 4 9]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [4]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[1:3])
print(a[1:])
print(a[:4])
print(a[-4:-2])
print(a[1:5])
print(a[1:5:2])
print(a[1:5:1])
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(a)
b = a[::-1]  # reversed a
print(b)
for i in b:
    print(i**(1/3))

[  0   1   8  27  64 125 216 343 512 729]
8
[1 8]
[  1   8  27  64 125 216 343 512 729]
[ 0  1  8 27]
[216 343]
[ 1  8 27 64]
[ 1 27]
[ 1  8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
8.999999999999998
7.999999999999999
6.999999999999999
5.999999999999999
5.0
9.999999999999998
3.0
9.999999999999998
1.0
9.999999999999998


Examples of two-dimensional arrays are

In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2[1,:])
print(arr2[:,1])
print(arr2[1,1:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[2 7]
[7 8 9]


### NumPy manipulation routines
There are a number of functions for array manipulation. Let's take look at a few of them.
A complete list can be found in the reference below.

Reference: `https://numpy.org/doc/stable/reference/routines.array-manipulation.html`

In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(np.shape(x)) # returns the array shape which is the same as matrix dimension
print(x.shape)     # shape is a properity of numpy.array 

# we can change the array shape
y = np.reshape(x,[3,2])
print(y)
print(y.shape)     #  array shape 

# flatten an array
z = x.flatten()
print(z)
print(z.shape)

# transpose
y = x.T  # matrix transpose of x
print(y)
z = np.transpose(x)  # same as x.T
print(z)

y = np.insert(x, [1], [[3,4,5]], axis=0)  # axis = 0 means the row 
print(y)
z = np.insert(x, [1], [[3],[4]], axis=1)  # axis = 0 means the column 
print(z)

y = np.fliplr(x) # reverse the order elements along the row axis (or reverse left and right)
y = np.flipud(x) # reverse the order elements along the col axis (or reverse up and down)


a = np.arange(9).reshape(3, 3)
print(a)
b = np.diagonal(a) # get the diagonal elelments
print(b)
c = np.fliplr(a).diagonal()  # fliplr and then get the diagonal elements
print(c)
d = np.flipud(a).diagonal()  # flipup and then get the diagonal elements
print(d)


### numpy.linalg
Since matrix can be easily represented by a NumPy `array`, NumPy contains a `linalg` submodule that provides various linear algebra functions.  

Reference: `https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg`

In [20]:
import numpy as np
from numpy import linalg
A = np.array([[1,2],[3,4]])
print(A)
print(linalg.det(A)) # determinant of A
B = linalg.inv(A) # inverse of A
print(B)
w, v = linalg.eig(A) # eigen values and normalized eigenvectors
print(w)
print(v) # each column of v is a normlized eigenvector associated with w in the same order. 

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Logic Functions

Reference: `https://numpy.org/doc/stable/reference/routines.logic.html`

In [21]:
x = np.array([0,1,1]) # x is a numpy array
print(x == 0)        # check if each element is zero
print(np.all(x==0))  # check if all elements are zero
print(np.any(x==0))  # check if any elemnent is zero
print((x==0).all())  # check if all elements are zero
print((x==0).any())  # check if any elemnent is zero
y=[0,1,1]            # y is a list
print(np.all(y==0))  # np.all() takes a list argument
print((y==0).all())  # a list object does not have all() method.

[ True False False]
False
True
False
True
False


AttributeError: 'bool' object has no attribute 'all'

In [11]:
x = np.cos(np.pi/2) # cos(90)
print(x) # x is not zero
print(x == 0)  # returns false
print(np.isclose(x,0)) # returns true

6.123233995736766e-17
False
True


There are infinitely many real numbers, but we have a limited memory space to store a floating number, e.g., **32**-bit floating-point numbers or **64**-bit double-precision numbers. For this reason, most real numbers cannot be precisely represented.  For example, we can represent 1.09 using a floating point.

In [12]:
x = 1.09
print(x*100 == 109)  # returns false
print(np.isclose(x*100, 109))  #returns true
print(x)
print("%.24f"%(x))

False
True
1.09
1.090000000000000079936058


In [15]:
print(1+2==3)  # Is it true or false?
print(0.1+0.2==0.3)  # Is it true or false?

True
False


We also cannot precisely represent irrational number, such as $\pi$ and $\sqrt{3}$.  Remember that there are always numerical errors. For example, 

In [14]:
x = np.sqrt(3)
print(x**2 == 3)
print(x)
print(x**2)
print(np.isclose(x, np.sqrt(3)))

False
1.7320508075688772
2.9999999999999996
True


**Rule of thumb**:  You must not use `==` for floating-point numbers and be very careful with `<` and `>` for floating-point numbers. Companies like Intel and Google never allow their programmers to use them for floating-point numbers. Intel once lost millions of dollars for a use of them and it had to redesign its chip.

For Fall 2022
Object oriented programming

In [17]:
x = [1,2,3,4,5]
print(x)
y = x
print(y)
y[1] = 9
print(y)
print(x)

x = [1,2,3,4,5]
print(x)
y = x.copy()
print(y)
y[1] = 9
print(y)
print(x)

x = [1,[0,1,2],3,4,5]
print(x)
y = x.copy()
print(y)
y[0] = 8
print(y)
print(x)
y[1][1] = 9
print(y)
print(x)

import copy
x = [1,[0,1,2],3,4,5]
print(x)
y = copy.deepcopy(x)
print(y)
y[1][1] = 9
print(y)
print(x)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 9, 3, 4, 5]
[1, 9, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 9, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[8, [0, 1, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[8, [0, 9, 2], 3, 4, 5]
[1, [0, 9, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[8, [0, 1, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]
[8, [0, 9, 2], 3, 4, 5]
[1, [0, 1, 2], 3, 4, 5]


<hr>

## Homework

### Problem 1
Create a folder called `ICE2` in your repository. Download tic-tac-toe.py from Teams and move it to the `ICE2` folder.  Complete the `check_game` function and push the code to your repository.

In [ ]:
import numpy as np

board_size = 3

board = np.zeros([board_size, board_size], dtype="int")
"""
If board_size = 4, board will be
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
"""


def display_board():
    """
    Display the current game board
    :return: None
    """
    print("_______")
    for row in board:
        print(row)


def update_board(player, row, col):
    """
    Update the current board. If the row and column index is already played,
    it will not update the board and return False.
    :param player: Player ID. It must be 1 or 2
    :param row: the row index of the game board
    :param col: the column index of the game board
    :return: True if the game board is successfully updated.
    and False if there are errors.
    """
    if player < 1 or player > 2:
        print("Error: player must be either 1 or 2.")
        return False

    if row < 0 or row > board_size or col < 0 or col > board_size:
        print("Error: invalid row or column index.")
        return False

    if board[row][col] != 0:
        print(f"Error: Row:{row} Col:{col} has already been played.")
        return False

    # updated the current game board.
    board[row][col] = player
    return True


def check_game():
    """
    Print the winner of the game if the game is over.
    :return: True if the game is over and False if not.
    """
    # Check if the game is won horizontally
    # Print "Player X wins horizontally" if player X wins the game. 
    for row in board:
        if row[0] != 0 and np.all(row == row[0]):
            print(f"Player {row[0]} wins horizontally")
            return True

    # Check if the game is won vertically.
    # Print "Player X wins vertically" if player X wins the game. 
    # write your code here
    

    # Check if the game is won diagonally
    # Print "Player X wins diagonally" if player X wins the game. 
    # write your code here

    
    # Check if the game is won anti-diagonally
    # Print "Player X wins anti-diagonally" if player X wins the game. 
    # write your code here
    
    
    # Check if the game is a draw - no zero left in the board
    # Print "The game is a draw" if so.
    # write your code here

    
    
    # return False if the game is not over.
    return False


def main():

    players = [1, 2]
    current_player = 0
    while True:
        display_board()
        row = input(f"Player {players[current_player]}: Enter the row you want to play (0,...,{board_size-1}): ")
        col = input(f"Player {players[current_player]}: Enter the column you want to play (0,...,{board_size-1}): ")

        if not update_board(players[current_player], int(row), int(col)):
            print("Play again")
            continue

        if check_game():
            display_board()
            break

        current_player ^= 1


if __name__ == '__main__':
    main()


### Problem 2
Write a Python function that finds ZYX Euler angles from a rotation matrix. 

In [ ]:
import numpy as np

def get_rpy(R):
    """
    Find the ZYX Euler angles (psi, theta, phi) from rotation matrix R
    :param R: a 3 by 3 numpy array representing a rotation in 3-D. 
    :return: ZYX Euler angels (psi, theta, phi)
   
    """
    # write your code here
    
    
    
    
    
    return psi, theta, phi
    
    

def main():

    for i in range(100):
        alpha = np.random.uniform(-np.pi, np.pi)
        beta = np.random.uniform(-np.pi, np.pi)
        gamma = np.random.uniform(-np.pi, np.pi)

        Rz = np.array([[np.cos(alpha), -np.sin(alpha), 0],
                       [np.sin(alpha), np.cos(alpha), 0],
                       [0,             0,             1]])
        Ry = np.array([[np.cos(beta),  0, np.sin(beta)],
                       [0,             1,            0],
                       [-np.sin(beta), 0, np.cos(beta)]])
        Rx = np.array([[1,             0,             0],
                       [0, np.cos(gamma), -np.sin(gamma)],
                       [0, np.sin(gamma), np.cos(gamma)]])

        R = Rz@Ry@Rx

        psi, theta, phi = get_rpy(R)

        Rz2 = np.array([[np.cos(psi), -np.sin(psi), 0],
                       [np.sin(psi), np.cos(psi), 0],
                       [0,             0,             1]])
        Ry2 = np.array([[np.cos(theta),  0, np.sin(theta)],
                       [0,             1,            0],
                       [-np.sin(theta), 0, np.cos(theta)]])
        Rx2 = np.array([[1,             0,             0],
                       [0, np.cos(phi), -np.sin(phi)],
                       [0, np.sin(phi), np.cos(phi)]])

        R2 = Rz2@Ry2@Rx2

        num_errors = 0

        if np.allclose(R, R2):
            if np.isclose(alpha, psi) and np.isclose(beta, theta) and np.isclose(gamma, phi):
                print("Passed: all angles are the same")
            else:
                print("Passed: angles are different, but it is OK.")
                print(f"psi={np.rad2deg(psi):3.2f}, theta={np.rad2deg(theta):3.2f}, phi={np.rad2deg(phi):3.2f}")
                print(f"alpha={np.rad2deg(alpha):3.2f}, beta={np.rad2deg(beta):3.2f}, gamma={np.rad2deg(phi):3.2f}")
        else:
            num_errors += 1
            print("Error:")
            print(f"psi={np.rad2deg(psi):3.2f}, theta={np.rad2deg(theta):3.2f}, phi={np.rad2deg(phi):3.2f}")
            print(f"alpha={np.rad2deg(alpha):3.2f}, beta={np.rad2deg(beta):3.2f}, gamma={np.rad2deg(phi):3.2f}")

        print("-------------------------")

    print("============================")
    print("Test is done")
    print(f"You have {num_errors} errors.")


if __name__ == '__main__':
    main()
